--Q1) 프로시저를 확인해보자
SELECT * 
FROM USER_PROCEDURES;

--Q2) 소스까지 확인 해보자
SELECT *
FROM USER_SOURCE;

--Q3) 부서번호 10번인 사원의 사원번호, 이름, 급여를 구하는 프로시저 EX01을 작성해보자 
SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE DEPTNO = 20;

SELECT EMPNO, ENAME, SAL INTO :A, :B, :C
FROM EMP
WHERE DEPTNO = 20;

SELECT COUNT(*)
FROM EMP
WHERE DEPTNO = 30;

--GETDEPT FUNCTION 사용해보기
SELECT ENAME, EMPNO, SAL, GETDEPT(EMPNO) FROM EMP;

--Q4) 사번을 받아 연봉을 리턴하는 GETSAL FUNCTION을 만들어보자
SELECT EMPNO, ENAME, SAL, GETSAL(EMPNO) AS 연봉 FROM EMP;

--Q5) 사번을 받아 봉급을 리턴하는 GETBONG FUNCTION을 만들어보자
-- 단, 봉급 = 연봉 + 커미션
SELECT EMPNO 번호, ENAME 이름, SAL 급여, NVL(COMM, 0) 커미션, GETBONG(EMPNO) 봉급 FROM EMP;

--Q6) VIEW를 확인해보자!
SELECT * FROM MY_VIEW;
INSERT INTO MY_VIEW VALUES(9999, 'JUSTIN', 300); --VIEW의 컬럼은 3개니까 3개만 입력
--원본 확인
SELECT * FROM EMP;
-- MY_VIEW를 통해 부서번호 추가 
INSERT INTO MY_VIEW(EMPNO, ENAME, SAL, DEPTNO) VALUES(999, 'BRUNO', 300, 20);
--> VIEW에 없는 COLUMN은 추가 불가능!!
INSERT INTO EMP(EMPNO, ENAME, SAL, DEPTNO) VALUES(999, 'BRUNO', 300, 20);

SELECT * FROM EMP;

DELETE FROM EMP
WHERE ENAME = 'JUSTIN' OR ENAME = 'BRUNO';
