-- 1. 사원들의 이름, 부서번호, 부서이름을 출력하라.

--ORACLE

SELECT ENAME, DEPT.DEPTNO, DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO;


-- ANSI

SELECT ENAME, DEPTNO, DNAME
FROM EMP JOIN DEPT USING(DEPTNO);



-- 2. DALLAS에서 근무하는 사원의 이름, 직위, 부서번호, 부서이름을
-- 출력하라.

--ORACLE

SELECT ENAME, JOB, DEPT.DEPTNO, DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO AND LOC='DALLAS';


--ANSI

SELECT ENAME, JOB, DEPTNO, DNAME
FROM EMP RIGHT OUTER JOIN DEPT USING(DEPTNO)
WHERE LOC='DALLAS';


 
-- 3. 이름에 'A'가 들어가는 사원들의 이름과 부서이름을 출력하라.

--ORACLE

SELECT ENAME, DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO AND ENAME LIKE '%A%';


--ANSI

SELECT ENAME, DNAME
FROM EMP JOIN DEPT USING(DEPTNO)
WHERE ENAME LIKE '%A%';



-- 4. 사원이름과 그 사원이 속한 부서의 부서명, 그리고 월급을 
--출력하는데 월급이 3000이상인 사원을 출력하라.

--ORACLE

SELECT ENAME, DNAME, SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO AND SAL>=3000;


--ANSI

SELECT ENAME, DNAME, SAL
FROM EMP JOIN DEPT USING(DEPTNO)
WHERE SAL>=3000;


 
-- 5. 직위가 'SALESMAN'인 사원들의 직위와 그 사원이름, 그리고
-- 그 사원이 속한 부서 이름을 출력하라.

--ORACLE

SELECT ENAME, JOB, DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO AND JOB='SALESMAN';


--ANSI

SELECT ENAME, JOB, DNAME
FROM EMP JOIN DEPT USING(DEPTNO)
WHERE JOB='SALESMAN';



-- 6. 커미션이 책정된 사원들의 사원번호, 이름, 연봉, 연봉+커미션,
-- 급여등급을 출력하되, 각각의 컬럼명을 '사원번호', '사원이름',
-- '연봉','실급여', '급여등급'으로 하여 출력하라.

--ORACLE

SELECT EMPNO AS 사원번호, ENAME AS 사원이름, SAL*12 연봉, 
COMM+SAL*12 AS 실급여, GRADE AS 급여등급
FROM EMP E, SALGRADE S
WHERE SAL BETWEEN LOSAL AND HISAL AND COMM IS NOT NULL;


--ANSI

SELECT EMPNO, ENAME, SAL*12, COMM+SAL*12, GRADE
FROM EMP JOIN SALGRADE ON 
SAL BETWEEN LOSAL AND HISAL AND COMM IS NOT NULL;



-- 7. 부서번호가 10번인 사원들의 부서번호, 부서이름, 사원이름,
-- 월급, 급여등급을 출력하라.

--ORACLE

SELECT D.DEPTNO, D.DNAME, E.ENAME, E.SAL, S.GRADE
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO=D.DEPTNO AND D.DEPTNO=10
AND SAL BETWEEN LOSAL AND HISAL;


--ANSI

SELECT DEPTNO, DNAME, ENAME, SAL, GRADE
FROM EMP JOIN DEPT USING(DEPTNO)
JOIN SALGRADE ON SAL BETWEEN LOSAL AND HISAL
WHERE DEPTNO=10;



-- 8. 부서번호가 10번, 20번인 사원들의 부서번호, 부서이름, 
-- 사원이름, 월급, 급여등급을 출력하라. 그리고 그 출력된 
-- 결과물을 부서번호가 낮은 순으로, 월급이 높은 순으로 
-- 정렬하라.

--ORACLE

SELECT D.DEPTNO, D.DNAME, E.ENAME, E.SAL, S.GRADE
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO=D.DEPTNO AND D.DEPTNO IN(10,20) 
AND SAL BETWEEN LOSAL AND HISAL
ORDER BY 1 ASC, 4 DESC; 


--ANSI

SELECT DEPTNO, DNAME, ENAME, SAL, GRADE
FROM EMP JOIN DEPT USING(DEPTNO)
JOIN SALGRADE ON SAL BETWEEN LOSAL AND HISAL AND DEPTNO IN(10,20)
ORDER BY 1 ASC, 4 DESC;
  
 

-- 9. 사원번호와 사원이름, 그리고 그 사원을 관리하는 관리자의 
-- 사원번호와 사원이름을 출력하되 각각의 컬럼명을 '사원번호',
-- '사원이름', '관리자번호', '관리자이름'으로 하여 출력하라.

--ORACLE

SELECT E1.EMPNO AS 사원번호, E1.ENAME AS 사원이름, E2.EMPNO AS 관리자번호, E2.ENAME AS 관리자이름
FROM EMP E1, EMP E2
WHERE E1.MGR=E2.EMPNO(+);


--ANSI

SELECT E1.EMPNO AS 사원번호, E1.ENAME AS 사원이름, E2.EMPNO AS 관리자번호, E2.ENAME AS 관리자이름
FROM EMP E1
LEFT OUTER JOIN EMP E2 ON E1.MGR=E2.EMPNO;



-10. 자신의 관리자보다 먼저 입사한 모든 사원의 이름 및 입사일을 해당 
--관리자의 이름 및입사일과 함게 표시하고 열 이름을 각각 
--EMPLOYEE,EMPHIREDATE,MANAGER,MGRHIREDATE로 저장한다.

 --ORACLE

SELECT E1.ENAME AS EMPLOYEE, E1.HIREDATE AS EMPHIREDATE, E2.ENAME AS MANAGER, E2.HIREDATE AS MGRHIREDATE
FROM EMP E1, EMP E2
WHERE E1.MGR=E2.EMPNO(+) AND
E1.HIREDATE<E2.HIREDATE;


--ANSI

SELECT E1.ENAME AS EMPLOYEE, E1.HIREDATE AS EMPHIREDATE, E2.ENAME AS MANAGER, E2.HIREDATE AS MGRHIREDATE
FROM EMP E1
JOIN EMP E2 ON E1.MGR=E2.EMPNO AND
E1.HIREDATE<E2.HIREDATE;



--11. 해당 부서의 모든 사원에 대한 부서 이름, 위치, 사원 수 및 평균 급여를 
--표시하는 정의를 작성한다. 
--열 이름을 각각 DNAME,LOC,NUMBER OF PEOPLE,SALARY로 한다.

--ORACLE

SELECT DNAME, LOC, COUNT(ENAME) AS "NUMBER OF PEOPLE", AVG(SAL) AS SALARY
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
GROUP BY DNAME, LOC;


--ANSI

SELECT  DNAME, LOC, COUNT(ENAME) AS "NUMBER OF PEOPLE", AVG(SAL) AS SALARY
FROM EMP JOIN DEPT USING(DEPTNO)
GROUP BY DNAME,LOC;

 
